function handles = mainframe
% 期权Straddle交易主界面
%handles = UIFrame.mainframe
% 吴云峰 20170410


%% 主交易界面:output
srsz = [1, 1, 1366, 768];
backcolor   = [1, 0.95, 0.85];
tbbackcolor = [0.8 1 0.8;0.6 1 1];
hFig_srsz = [srsz(1) srsz(2) srsz(3)*0.95 srsz(4)*0.875];
handles.output = figure('Position', hFig_srsz, 'ToolBar', 'none', 'Menubar', 'none', ...
    'Color', backcolor);
set(handles.output, 'Name', '期权Straddle交易', 'NumberTitle', 'off')
movegui(handles.output, 'north')
parent = handles.output;


%% 账户选择框架:accountsel
handles.accountsel.panelbox = uipanel('Parent', parent, 'Title', '账户选择', ...
    'Units', 'Normalized', 'Position', [0.005 0.942 0.99 0.057], 'FontSize', 9, ...
    'FontWeight', 'bold', 'TitlePosition', 'leftbottom');
panelbox = handles.accountsel.panelbox;
handles.accountsel.popup_accountsel = uicontrol('Parent', panelbox, 'style', 'popupmenu', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'w', 'String', {'账户选择'}, ...
    'Units', 'Normalized', 'Position', [0.05 0.005 0.1 0.99], 'FontSize', 9, ...
    'FontWeight', 'bold');
handles.accountsel.edit_accountname = uicontrol('Parent', panelbox, 'style', 'edit', ...
    'Backgroundcolor', 'w', 'String', '2016 | 2601 | 2034', 'Units', 'Normalized', ...
    'Position', [0.16 0.005 0.18 0.99], 'FontSize', 9, 'FontWeight', 'bold', ...
    'Enable', 'Inactive');
handles.accountsel.text_proportion  = uicontrol('Parent', panelbox, 'style', 'text', ...
    'String', '账户比例(使用/符号间隔,按账户名称顺序排序)', 'Units', 'Normalized', 'Position', [0.34 0.005 0.25 0.99], ...
    'FontSize', 9, 'FontWeight', 'bold');
handles.accountsel.edit_preproportion   = uicontrol('Parent', panelbox, 'style', 'edit', ...
    'Backgroundcolor', 'w', 'String', '1/1/1', 'Units', 'Normalized', ...
    'Position', [0.59 0.005 0.08 0.99], 'FontSize', 9, 'FontWeight', 'bold', 'Enable', 'on');
% 账户比例的设置
handles.accountsel.button_setproportion = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'String', '账户比率设置', 'Units', 'Normalized', ...
    'Position', [0.68 0.005 0.08 0.99], 'FontSize', 9, 'FontWeight', 'bold', ...
    'Foregroundcolor', 'r');
handles.accountsel.edit_aftproportion   = uicontrol('Parent', panelbox, 'style', 'edit', ...
    'Backgroundcolor', 'w', 'String', '1:1:1', 'Units', 'Normalized', ...
    'Position', [0.765 0.005 0.08 0.99], 'FontSize', 9, 'FontWeight', 'bold', ...
    'Enable', 'Inactive');
% 将所有的Book进行保存设置
handles.accountsel.button_saveallbooks  = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', '所有Book保存', ...
    'Units', 'Normalized', 'Position', [0.86 0.005 0.1 0.99], 'FontSize', 9, ...
    'FontWeight', 'bold');


%% 标的资产框架:asset
handles.asset.panelbox = uipanel('Parent', parent, 'Title', '标的资产', ...
    'Units', 'Normalized', 'Position', [0.005 0.61 0.99 0.33], 'FontSize', 9, ...
    'FontWeight', 'bold', 'TitlePosition', 'leftbottom');
panelbox = handles.asset.panelbox;
handles.asset.table_optopensel  = uitable('Parent', panelbox, 'Units', 'Normalized', ...
    'Position', [0.001 0.01 0.498 0.98], 'FontSize' , 9 , 'FontWeight' ,'bold', ...
    'Data', num2cell(ones(8, 17)*2.8), 'ColumnWidth', num2cell(ones(1,17)*45), 'BackgroundColor', tbbackcolor);
handles.asset.table_optclosesel = uitable('Parent', panelbox, 'Units', 'Normalized', ...
    'Position', [0.501 0.01 0.498 0.98], 'FontSize' , 9 , 'FontWeight' ,'bold', ...
    'Data', num2cell(ones(8, 17)*2.8), 'ColumnWidth', num2cell(ones(1,17)*45), 'BackgroundColor', tbbackcolor);


%% payoff作图框架:payofffig
handles.payofffig.panelbox = uipanel('Parent', parent, 'Title', 'payoff作图', ...
    'Units', 'Normalized', 'Position', [0.005 0.002 0.445 0.605], 'FontSize', 9, ...
    'FontWeight', 'bold', 'TitlePosition', 'leftbottom');
panelbox = handles.payofffig.panelbox;
handles.payofffig.axes_payoff  = axes('Parent', panelbox, 'Units', 'Normalized', ...
    'Position', [0.1 0.35 0.87 0.63], 'FontSize', 9, 'FontWeight', 'bold');
handles.payofffig.table_greeks = uitable('Parent', panelbox, 'Units', 'Normalized',...
    'Position', [0.001 0.005 0.798 0.285], 'FontSize' , 9 , 'FontWeight' ,'bold', ...
    'Data', num2cell(ones(4,8)*0.88), 'BackgroundColor', tbbackcolor);
set(handles.payofffig.table_greeks, 'ColumnWidth', num2cell([66, ones(1,7) * 50]))
set(handles.payofffig.table_greeks, 'ColumnName' , {'代码','数量', '价格','IV','1%Δ','1%Γ','1%ν','日θ'})

handles.payofffig.text_minpx   = uicontrol('Parent', panelbox, 'style', 'text', ...
    'Units', 'Normalized', 'Position', [0.8 0.24 0.08 0.045], 'FontSize' , 9 , ...
    'FontWeight' ,'bold', 'String', 'min');
handles.payofffig.edit_minpx   = uicontrol('Parent', panelbox, 'style', 'edit', ...
    'Units', 'Normalized', 'Position', [0.89 0.24 0.1 0.05], 'FontSize' , 9 , ...
    'FontWeight' ,'bold', 'String', '2.2', 'Backgroundcolor', 'w');
handles.payofffig.text_maxpx   = uicontrol('Parent', panelbox, 'style', 'text',...
    'Units', 'Normalized', 'Position', [0.8 0.18 0.08 0.045], 'FontSize' , 9 , ...
    'FontWeight' ,'bold', 'String', 'max');
handles.payofffig.edit_maxpx    = uicontrol('Parent', panelbox, 'style', 'edit', ...
    'Units', 'Normalized', 'Position', [0.89 0.18 0.1 0.05], 'FontSize' , 9 , ...
    'FontWeight' ,'bold', 'String', '2.5', 'Backgroundcolor', 'w');
handles.payofffig.text_interval = uicontrol('Parent', panelbox, 'style', 'text',...
    'Units', 'Normalized', 'Position', [0.85 0.125 0.08 0.045], 'FontSize' , 9 , ...
    'FontWeight' ,'bold', 'String', 'interval');
handles.payofffig.edit_interval = uicontrol('Parent', panelbox, 'style', 'edit', ...
    'Units', 'Normalized', 'Position', [0.85 0.065 0.1 0.05], 'FontSize' , 9 , ...
    'FontWeight' ,'bold', 'String', '0.05', 'Backgroundcolor', 'w');


%% 操作框架:operation
handles.operation.panelbox = uipanel('Parent', parent, 'Title', '操作', ...
    'Units', 'Normalized', 'Position', [0.451 0.002 0.548 0.19], 'FontSize', 9, ...
    'FontWeight', 'bold', 'TitlePosition', 'leftbottom');
panelbox = handles.operation.panelbox;
handles.operation.button_entrustalloppo  = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', '全对价', ...
    'Units', 'Normalized', 'Position', [0.005 0.02 0.1 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold');
handles.operation.button_entrusthalfpend = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', '半对半挂', ...
    'Units', 'Normalized', 'Position', [0.005 0.26 0.1 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold');
handles.operation.button_entrustallpend  = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', '全挂', ...
    'Units', 'Normalized', 'Position', [0.005 0.5 0.1 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold');
handles.operation.checkbox_entrustchase  = uicontrol('Parent', panelbox, 'style', 'checkbox', ...
    'String', '追单', 'Units', 'Normalized', 'Position', [0.005 0.74 0.1 0.22], ...
    'FontSize', 9, 'FontWeight', 'bold', 'value', 0);

handles.operation.button_payoffinfo      = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', 'payoff作图', ...
    'Units', 'Normalized', 'Position', [0.115 0.02 0.14 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold');
handles.operation.button_optamtreset     = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', '交易数量重置', ...
    'Units', 'Normalized', 'Position', [0.115 0.26 0.14 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold');
px_str = {'最新';'对手1';'对手2';'对手3';'对手4';'对手5'};
handles.operation.popup_oppositeprice    = uicontrol('Parent', panelbox, 'style', 'popupmenu', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'y', 'String', px_str , ...
    'Units', 'Normalized', 'Position', [0.115 0.5 0.14 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold', 'Value', 2);
px_str = {'最新';'挂单1';'挂单2';'挂单3';'挂单4';'挂单5'};
handles.operation.popup_guadanprice      = uicontrol('Parent', panelbox, 'style', 'popupmenu', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'y', 'String', px_str , ...
    'Units', 'Normalized', 'Position', [0.115 0.74 0.14 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold', 'Value', 2);

handles.operation.button_optquote   = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', '组合行情', ...
    'Units', 'Normalized', 'Position', [0.265 0.02 0.14 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold');
handles.operation.button_bdquote    = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', '标的行情', ...
    'Units', 'Normalized', 'Position', [0.265 0.26 0.14 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold');
handles.operation.button_querytotally   = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', '一键查询', ...
    'Units', 'Normalized', 'Position', [0.265 0.5 0.14 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold');
handles.operation.button_canceltotally  = uicontrol('Parent', panelbox, 'style', 'pushbutton', ...
    'Backgroundcolor', 'k', 'Foregroundcolor', 'r', 'String', '一键撤单', ...
    'Units', 'Normalized', 'Position', [0.265 0.74 0.14 0.22], 'FontSize', 9, ...
    'FontWeight', 'bold');


%% 行情框架:quote
handles.quote.panelbox    = uipanel('Parent', parent, 'Title', '行情',...
    'Units', 'Normalized', 'Position', [0.451 0.195 0.548 0.415], 'FontSize', 9, ...
    'FontWeight', 'bold', 'TitlePosition', 'leftbottom');
panelbox = handles.quote.panelbox;
optquote = cell(11, 4);
optquote(:, 1)   = {'卖5价';'卖4价';'卖3价';'卖2价';'卖1价';'最新价';'买1价';'买2价';'买3价';'买4价';'买5价'};
optquote(:, end) = {'卖5量';'卖4量';'卖3量';'卖2量';'卖1量';'最新量';'买1量';'买2量';'买3量';'买4量';'买5量'};
optquote(:, 2:3) = num2cell(0.8888*ones(11,2));
handles.quote.table_quote = uitable('Parent', panelbox, 'Units', 'Normalized', ...
    'Position', [0.001 0.005 0.297 0.99], 'FontSize' , 9 , 'FontWeight' ,'bold', ...
    'Data', optquote, 'ColumnName', '', 'RowName', '', ...
    'ColumnWidth', num2cell([50,50,50,50]), 'BackgroundColor', [0.8 1 0.8;0.6 1 1]);
handles.quote.axes_quote  = axes('Parent', panelbox, 'Units', 'Normalized', ...
    'Position', [0.37 0.07 0.6 0.91], 'FontSize', 9, 'FontWeight', 'bold');










end